# Generated by Django 3.2.6 on 2021-08-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_rename_obon_name_result_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='user_name',
            field=models.CharField(default='名無し', max_length=255),
        ),
        migrations.AlterField(
            model_name='obon',
            name='name',
            field=models.CharField(default='Bonta', max_length=255),
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(default='Bonta', max_length=255),
        ),
    ]
